apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  # Use kubectl port-forward svc/frontend-service 3000:80 to open in browser.
