apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-tracker-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aftaab60/gitops-playground.git
    targetRevision: main
    path: manifests/staging        # only this line differs from dev
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-staging      # and this one
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
