apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# All resources in this overlay will be placed into the gitops-dev namespace.
namespace: gitops-dev
resources:
- namespace.yaml # create the namespace first
- ../base # inherit all base resources
# Kargo updates newTag here when promoting a new nginx version to dev.
images:
- name: nginx
  newTag: 1.31.2
# Patch only what changes between dev and prod.
patches:
- path: app-config-patch.yaml
  target:
    kind: ConfigMap
    name: app-config
- path: api-patch.yaml
  target:
    kind: Deployment
    name: api
