apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-staging

resources:
  - namespace.yaml
  - ../base

patches:
  - path: app-config-patch.yaml
    target:
      kind: ConfigMap
      name: app-config
  - path: api-patch.yaml
    target:
      kind: Deployment
      name: api
  - path: frontend-patch.yaml
    target:
      kind: Deployment
      name: frontend
